### ISSUE TITLE
Sending photos

### ISSUE THREAD

**Issue by DominikIlski** [tedcrimson/firebase_chat#1]
Hello, 
i have problem with sending images.
When i try to send edited photo, app freezes and the error apears.
```
I/flutter (13938): Picture saved to /data/user/0/com.dominik_ilski.people_craft/app_flutter/Pictures/flutter_test/1610888362001.jpg
E/flutter (13938): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type '_Uint8ArrayView' is not a subtype of type 'DrawPage' of 'result'
E/flutter (13938): #0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
package:flutter/…/widgets/routes.dart:1
E/flutter (13938): #1      _RouteEntry.pop
package:flutter/…/widgets/navigator.dart:2483
E/flutter (13938): #2      NavigatorState.pop
package:flutter/…/widgets/navigator.dart:3825
E/flutter (13938): #3      _DrawPageState.build.<anonymous closure>
package:draw_page/src/draw_page.dart:275
E/flutter (13938): <asynchronous suspension>
E/flutter (13938): #4      _DrawPageState.build.<anonymous closure> (package:draw_page/src/draw_page.dart)
package:draw_page/src/draw_page.dart:1
E/flutter (13938): #5      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter (13938): #6      _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter (13938): #7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (13938): #8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (13938): #9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (13938): #10     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:222
E/flutter (13938): #11     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:476
E/flutter (13938): #12     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:77
E/flutter (13938): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (13938): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (13938): #15     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:120
E/flutter (13938): #16     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:106
E/flutter (13938): #17     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:358
E/flutter (13938): #18     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter (13938): #19     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter (13938): #20     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter (13938): #21     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter (13938): #22     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter (13938): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (13938): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13938): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (13938): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (13938): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (13938):
```

The differences in my code compared to the example are:
```
  @override
  Future getImage() async {
    List<Uint8List> images;
    // Coming soon
    // if (kIsWeb) {
    //   var file = await FilePicker.getFile();

    //   if (file != null) {
    //     var g = await _getHtmlFileContent(file);
    //     images = [g];
    //   }
    // } else {
    images = await Navigator.of(context).push<List<Uint8List>>(
        MaterialPageRoute(builder: (context) => CameraPage()));
    if (images != null && images.length == 1) {
      var image = await Navigator.of(context)
          .push(MaterialPageRoute<DrawPage>(builder: (context) 
        => DrawPage(
            imageData: images[0] as Uint8List, loadingWidget: loadingWidget)
      ));
      if (image == null) return null;
      images = <Uint8List>[image.imageData];
      // }
    }

    if (images != null) {
      for (var image in images) {
        await sendImage(image);
      }
    }
  }
```

I am using analysis_options in my projest, so thats why i had to give lists a type
```
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

**Comment by tedcrimson** [comment]
> Hello,
> i have problem with sending images.
> When i try to send edited photo, app freezes and the error apears.
> 
> ```
> I/flutter (13938): Picture saved to /data/user/0/com.dominik_ilski.people_craft/app_flutter/Pictures/flutter_test/1610888362001.jpg
> E/flutter (13938): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type '_Uint8ArrayView' is not a subtype of type 'DrawPage' of 'result'
> E/flutter (13938): #0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
> package:flutter/…/widgets/routes.dart:1
> E/flutter (13938): #1      _RouteEntry.pop
> package:flutter/…/widgets/navigator.dart:2483
> E/flutter (13938): #2      NavigatorState.pop
> package:flutter/…/widgets/navigator.dart:3825
> E/flutter (13938): #3      _DrawPageState.build.<anonymous closure>
> package:draw_page/src/draw_page.dart:275
> E/flutter (13938): <asynchronous suspension>
> E/flutter (13938): #4      _DrawPageState.build.<anonymous closure> (package:draw_page/src/draw_page.dart)
> package:draw_page/src/draw_page.dart:1
> E/flutter (13938): #5      _InkResponseState._handleTap
> package:flutter/…/material/ink_well.dart:993
> E/flutter (13938): #6      _InkResponseState.build.<anonymous closure>
> package:flutter/…/material/ink_well.dart:1111
> E/flutter (13938): #7      GestureRecognizer.invokeCallback
> package:flutter/…/gestures/recognizer.dart:183
> E/flutter (13938): #8      TapGestureRecognizer.handleTapUp
> package:flutter/…/gestures/tap.dart:598
> E/flutter (13938): #9      BaseTapGestureRecognizer._checkUp
> package:flutter/…/gestures/tap.dart:287
> E/flutter (13938): #10     BaseTapGestureRecognizer.handlePrimaryPointer
> package:flutter/…/gestures/tap.dart:222
> E/flutter (13938): #11     PrimaryPointerGestureRecognizer.handleEvent
> package:flutter/…/gestures/recognizer.dart:476
> E/flutter (13938): #12     PointerRouter._dispatch
> package:flutter/…/gestures/pointer_router.dart:77
> E/flutter (13938): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
> package:flutter/…/gestures/pointer_router.dart:122
> E/flutter (13938): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> E/flutter (13938): #15     PointerRouter._dispatchEventToRoutes
> package:flutter/…/gestures/pointer_router.dart:120
> E/flutter (13938): #16     PointerRouter.route
> package:flutter/…/gestures/pointer_router.dart:106
> E/flutter (13938): #17     GestureBinding.handleEvent
> package:flutter/…/gestures/binding.dart:358
> E/flutter (13938): #18     GestureBinding.dispatchEvent
> package:flutter/…/gestures/binding.dart:338
> E/flutter (13938): #19     RendererBinding.dispatchEvent
> package:flutter/…/rendering/binding.dart:267
> E/flutter (13938): #20     GestureBinding._handlePointerEvent
> package:flutter/…/gestures/binding.dart:295
> E/flutter (13938): #21     GestureBinding._flushPointerEventQueue
> package:flutter/…/gestures/binding.dart:240
> E/flutter (13938): #22     GestureBinding._handlePointerDataPacket
> package:flutter/…/gestures/binding.dart:213
> E/flutter (13938): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
> E/flutter (13938): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> E/flutter (13938): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
> E/flutter (13938): #26     _invoke1 (dart:ui/hooks.dart:265:10)
> E/flutter (13938): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
> E/flutter (13938):
> ```
> 
> The differences in my code compared to the example are:
> 
> ```
>   @override
>   Future getImage() async {
>     List<Uint8List> images;
>     // Coming soon
>     // if (kIsWeb) {
>     //   var file = await FilePicker.getFile();
> 
>     //   if (file != null) {
>     //     var g = await _getHtmlFileContent(file);
>     //     images = [g];
>     //   }
>     // } else {
>     images = await Navigator.of(context).push<List<Uint8List>>(
>         MaterialPageRoute(builder: (context) => CameraPage()));
>     if (images != null && images.length == 1) {
>       var image = await Navigator.of(context)
>           .push(MaterialPageRoute<DrawPage>(builder: (context) 
>         => DrawPage(
>             imageData: images[0] as Uint8List, loadingWidget: loadingWidget)
>       ));
>       if (image == null) return null;
>       images = <Uint8List>[image.imageData];
>       // }
>     }
> 
>     if (images != null) {
>       for (var image in images) {
>         await sendImage(image);
>       }
>     }
>   }
> ```
> 
> I am using analysis_options in my projest, so thats why i had to give lists a type
> 
> ```
> analyzer:
>   strong-mode:
>     implicit-casts: false
>     implicit-dynamic: false
> ```

Sorry for the late reply.

Try like this:
```dart
@override
  Future getImage() async {
    List<Uint8List> images;
    // Coming soon
    // if (kIsWeb) {
    //   var file = await FilePicker.getFile();

    //   if (file != null) {
    //     var g = await _getHtmlFileContent(file);
    //     images = [g];
    //   }
    // } else {
    images = await Navigator.of(context)
        .push<List<Uint8List>>(MaterialPageRoute(builder: (BuildContext context) => CameraPage()));
    if (images != null && images.length == 1) {
      Uint8List image = await Navigator.of(context).push<Uint8List>(MaterialPageRoute(builder: (BuildContext context) {
        return DrawPage(imageData: images[0], loadingWidget: loadingWidget);
      }));
      if (image == null) return null;
      images = [image];
      // }
    }

    if (images != null) {
      for (var image in images) {
        await sendImage(image);
      }
    }
  }
```

**Comment by DominikIlski** [comment]
Thanks for the answer. The fix works and your package helped me a lot. From what I saw, your solution is the best available. I would like to support your work and thank you by buying you coffee. The same way it is done in others in other packages.

**Comment by tedcrimson** [comment]
I am glad that I helped you 😌
